version: "3.8"

services:
  client:
    build: ./front/bank-client
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DB_USER: MinecraftDB
      DB_PASSWORD: MinecraftDB
      DB_NAME: minecraft_bank
      DB_HOST: localhost
      DB_PORT: 5432
      JWT_SECRET: d4e0e5286f1a6a8d19bcaaed1b728d3e35c2cf0d8cfd9a05f7a08070cb404f4b9966bb2b1cfb2e51b3e6659e18c57bfa3ae5d4b16d2ed0f2821cb64c4c10f27f

volumes:
  pgdata:
