version: "3.8"

services:
  client:
    build: ./front/bank-client
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DB_USER: MinecraftDB
      DB_PASSWORD: MinecraftDB
      DB_NAME: minecraft_bank
      DB_HOST: localhost
      DB_PORT: 5432

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: MinecraftDB
      POSTGRES_PASSWORD: MinecraftDB
      POSTGRES_DB: minecraft_bank
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
